### ISSUE TITLE
Lanterns lack transparency

### ISSUE THREAD

**Issue by niraqw** [hjake123/eclectic#2]
The lantern added by this mod doesn't have transparent chains.

![2022-03-07_15 13 37](https://user-images.githubusercontent.com/22210045/157134497-9a7e8c0a-5469-46e7-a01a-f47db463ef8a.png)

Minecraft 1.18.2
Forge 40.0.12

Mod List:
eclectic-1.18.x-1.2

**Comment by hjake123** [comment]
Not sure how I missed this, thanks

**Comment by hjake123** [comment]
Fixed in 1.18.x-1.2a
