### ISSUE TITLE
Client Disconnect from server on use of item 'pointer'

### ISSUE THREAD

**Issue by StygianNights** [hjake123/eclectic#3]
Hi, doing a private server with some friends with your mod. 
Forge version is 39.1.2
Eclectic version is 1.2a
Picture is full modlist
![Captureforweirdbug](https://user-images.githubusercontent.com/51977199/159150265-588d8be1-67ef-4c12-9228-4b4daece2649.PNG)

> [05:45:16] [Server thread/FATAL]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
> [05:45:16] [Server thread/WARN]: Failed to handle packet for /98.198.185.158:56819
> net.minecraft.ReportedException: Ticking player
> 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
> 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:1.0]
> 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
> 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at com.hyperlynx.eclectic.items.Pointer.m_5929_(Pointer.java:71) ~[eclectic-1.18.x-1.2a.jar%23107!/:1.2]
> 	at net.minecraft.world.item.ItemStack.m_41731_(ItemStack.java:977) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.world.entity.LivingEntity.m_142106_(LivingEntity.java:2847) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.level.ServerPlayer.m_142106_(ServerPlayer.java:1567) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.world.entity.LivingEntity.m_21329_(LivingEntity.java:2838) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2212) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.1-20211210.034407-srg.jar%23220!/:?]
> 	... 9 more
> [05:45:16] [Server thread/INFO]: Stygian_Nights lost connection: Internal server error
> [05:45:16] [Server thread/INFO]: Stygian_Nights left the game

**Comment by hjake123** [comment]
I've patched the issue in 1,2b I believe, please let me know if it persists -- it's hard for me to test multiplayer interactions.

**Comment by hjake123** [comment]
I'll close this now.
